# This is a basic workflow to help you get started with Actions

name: CI


# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  echo_actions:
    name: Show File Changes
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: test
        run: |
          cat $HOME/files.json
          cat $HOME/files_modified.json
          cat $HOME/files_added.json
          cat $HOME/files_removed.json
          echo '${{ steps.file_changes.outputs.files}}'
          echo '${{ steps.file_changes.outputs.files_modified}}'
          echo '${{ steps.file_changes.outputs.files_added}}'
          echo '${{ steps.file_changes.outputs.files_removed}}'
      - name: HTTPClient
        uses: "swinton/httpie.action@master"
        with:
            args: POST httpbin.org/anything hello=${{ steps.file_changes.outputs.files }}
